mysunbuddy/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-

"""Define urls used in this application."""

from django.conf.urls import include, url
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    url(r'', include('rest_api.urls', namespace='rest_framework')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

# Change admin site title
admin.site.site_header = _("MySunBuddyinc Administration")
admin.site.site_title = _("MySunBuddyinc Admin")

rest_api/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-

"""Define urls used in rest_api application."""

from django.conf.urls import url

from rest_api import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^utility_mock$', views.utility_api_mock, name='utility_api_mock'),

    # user dashboard
    url(r'dashboard/$', views.UserDashboardView.as_view(), name='user-dashboard'),

    # callback urls
    url(r'^utility_api_callback$', views.utility_api_callback, name='utility_api_callback'),
    url(r'^dwolla_api_callback$', views.dwolla_api_callback, name='dwolla_api_callback'),
    url(r'^webhooks/dwolla$', views.webhook_dwolla, name='webhook_dwolla'),
    url(r'^api/login$', views.LoginView.as_view(), name="api_login"),
    url(r'^api/register$', views.RegisterView.as_view(), name="api_register"),
    url(r'^api/reportData', views.report_data, name="api_report_data"),
    url(r'^api/get-iav-token', views.get_iav_token, name="api_get_iav_token"),
    url(r'^api/get-profile', views.get_profile_data, name="api_get_profile"),
    url(r'^api/update-funding', views.update_funding, name="api_update_funding"),
    url(r'^api/remove-funding', views.remove_funding, name="api_remove_funding"),
    url(r'^api/business-classification', views.get_business_classification, name="api_get_business_classifications"),
    url(r'^api/solar/percent$', views.SolarPercentView.as_view(), name="api_solar_percent"),
    url(r'^api/account/edit$', views.EditProfileView.as_view(), name="api_edit_account"),
    url(r'^api/account/seller_setup$', views.SetupSellerFunding.as_view()),

    url(r'^api/account/beneficial_setup$', views.SetupBeneficialOwner.as_view()),
    url(r'^api/account/get_all_beneficials$', views.BeneficialOwnerList.as_view()),
    url(r'^api/account/certify_ownership$', views.certify_ownership_view),


    url(r'^api/account/verify-deposits$', views.VerifyDeposits.as_view()),
    url(r'^api/account/upload-verification-document$', views.UploadVerificationDocument.as_view()),
    url(r'^api/deals/(?P<deal_id>[0-9]+)/preview$', views.preview_contract),
    url(r'^api/deals/(?P<deal_id>[0-9]+)/sign$', views.SignDealView.as_view()),
    url(r'^api/deals/(?P<deal_id>[0-9]+)/deny$', views.DenyDealView.as_view(),
        name="api_deny_deals"),
    url(r'^api/deals$', views.DealView.as_view(), name="api_deals"),
    url(r'^api/installations$', views.AccountInstallationsView.as_view(), name="api_installations"),
    url(r'^api/installation/(?P<id>[0-9]+)$', views.InstallationView.as_view(), name="api_installation"),
    url(r'^api/create_installation$', views.CreateInstallationView.as_view(), name="api_create_installation"),
    url(r'^api/installation/(?P<id>[0-9]+)/edit$', views.EditInstallationView.as_view(), name="api_edit_installation"),
    url(r'^api/installation/(?P<id>[0-9]+)/deals$', views.InstallationDealView.as_view(), name="api_installation_deals"),
    url(r'^api/installation/(?P<id>[0-9]+)/transactions$', views.InstallationTransactionsView.as_view(),
        name="installation_transactions"),
    url(r'^api/installation/(?P<id>[0-9]+)/send_email$', views.InstallationEmailView.as_view(),
        name="email_customers"),
    url(r'^api/buyer/automatch$', views.BuyerAutomatchView.as_view(), name="api_buyer_automatch"),
    url(r'^api/buyer/code$', views.BuyerCommunityCodeView.as_view(), name="api_buyer_code"),

    url(r'^api/password/reset$', views.PasswordResetView.as_view(),
        name="api_reset_password"),

    # admin links

    url(r"^view_pending_transactions$", views.view_pending_transactions, name="view_pending_transactions"),
    url(r"^cancel_transaction/(?P<transaction_id>[0-9]+)$", views.cancel_transaction, name="cancel_transaction"),
    url(r"^execute_transactions$", views.execute_transactions, name="execute_transactions"),
    url(r"^add_community_solar$", views.add_community_solar, name="add_community_solar"),
    url(r"^admin/view_accounts$", views.admin_view_accounts, name="admin_view_accounts"),
    url(r'^api/credit/calculate/(?P<id>[0-9]+)$', views.PVWattsView.as_view(), name="api_calculate_credit"),
    url(r'^admin/view_set_manual_credits/(?P<account_id>[0-9]+)$', views.view_set_manual_credits, name="view_set_account_credits"),
    url(r'^admin/edit_manual_credits/(?P<account_id>[0-9]+)$', views.edit_manual_credits, name="edit_account_credits"),
    url(r'^admin/revert_from_manual/(?P<account_id>[0-9]+)$', views.revert_from_manual, name="revert_from_manual"),
]

templates/admin_page.html
{% extends "account/base.html" %}
{% load staticfiles %}
{% block content %}

    <p class="pull-right"><a href="/">Back to main site</a></p>
    <br>
    <h1>ACCOUNT STATS</h1>
    <p>Number of accounts (total):   {{ number_of_accounts }}</p>
    <p>Number of completed accounts:   {{ number_of_completed_accounts }}</p>
    <br>
    <a href="/admin/view_accounts" class="admin-button">VIEW ALL ACCOUNTS</a>
    <br>
    <br>
    {% if manual_credit_accounts %}
        <h2>Accounts requiring manual credit review</h2>
        <br>
        <table width="100%" class="admin-table">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Role
                </th>
                <th>
                    Average Monthly Credit
                </th>
                <th>
                    Percent to sell
                </th>
                <th>
                    Credit to sell
                </th>
                <th>
                    Reason for review
                </th>
            </tr>
            {% for account in manual_credit_accounts %}
            <tr>
                <td>
                    {{ account.name }}
                </td>
                <td>
                    {{ account.email }}
                </td>
                <td>
                    {{ account.role | upper }}
                </td>
                <td align="right">
                    {{ account.average_monthly_credit }}
                </td>
                <td align="right">
                    {{ account.credit_to_sell_percent }}%
                </td>
                <td align="right">
                    {{ account.credit_to_sell }}
                </td>
                <td>
                    {{ account.get_formatted_credit_review_reason }}
                </td>
                <td>
                    {% if account.credit_to_sell %}
                        <form method="POST" action="{% url 'rest_framework:view_set_account_credits' account.id %}">
                        {% csrf_token %}<input type="submit" value="Edit Monthly Credits"></form>
                    {% else %}
                        <form method="POST" action="{% url 'rest_framework:view_set_account_credits' account.id %}">
                        {% csrf_token %}<input type="submit" value="Set Monthly Credits"></form>
                    {% endif %}
                    <form method="POST" action="{% url 'rest_framework:revert_from_manual' account.id %}">
                        {% csrf_token %}<input type="submit" value="Revert back to UtilityAPI"></form>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h4 style="font-style: italic">No accounts requiring manual credit review</h4>
    {% endif %}
    <br>
    <br>
    <h1>TRANSACTIONS</h1>
    {% if incomplete_transactions %}
        <h2>Transactions pending administrator action</h2>
        <br>
        <table width="100%" class="admin-table">
            <tr>
                <th>
                    Buyer
                </th>
                <th>
                    Seller
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Fee
                </th>
                <th>
                    Created on
                </th>
                <th>
                    Actions
                </th>
            </tr>
            {% for transaction in incomplete_transactions %}
            <tr>
                <td>
                    {{ transaction.deal.buyer.email }}
                </td>
                <td>
                    {{ transaction.deal.seller.email }}
                </td>
                <td>
                    {{ transaction.paid_to_seller }}
                </td>
                <td>
                    {{ transaction.fee }}
                </td>
                <td>
                    {{transaction.created_on|date:"SHORT_DATE_FORMAT"}} {{transaction.created_on|time:"h:i a"}}
                </td>
                <td>
                  <form method="POST" action="{% url "rest_framework:cancel_transaction" transaction.id %}" class="cancel-trans-frm">
                  {% csrf_token %}<input type="submit" value="Cancel"></form>
                </td>
            </tr>
            {% endfor %}
        </table>
    <br>
    <p>
        <form method="POST" action="{% url "rest_framework:execute_transactions" %} ">
            {% csrf_token %}<input type="submit" value="Execute All Transactions">
        </form>
    </p>
    {% else %}
        <h4 style="font-style: italic">No transactions pending admin action</h4>
    {% endif %}
    <br>
    <br>
    {% if transactions_in_process %}
        <h2>Transactions being processed by Dwolla</h2>
        <br>
        <table width="100%" class="admin-table">
            <tr>
                <th>
                    Buyer
                </th>
                <th>
                    Seller
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Fee
                </th>
                <th>
                    Dwolla Status
                </th>
                <th>
                    Created on
                </th>
                <th>
                    Actions
                </th>
            </tr>
            {% for transaction in transactions_in_process %}
            <tr>
                <td>
                    {{ transaction.deal.buyer.email }}
                </td>
                <td>
                    {{ transaction.deal.seller.email }}
                </td>
                <td>
                    {{ transaction.paid_to_seller }}
                </td>
                <td>
                    {{ transaction.fee }}
                </td>
                <td>
                    {{ transaction.status }}
                </td>
                <td>
                    {{transaction.created_on|date:"SHORT_DATE_FORMAT"}} {{transaction.created_on|time:"h:i a"}}
                </td>

                <td>
                  <form method="POST" action="{% url "rest_framework:cancel_transaction" transaction.id %}" class="cancel-trans-frm">
                  {% csrf_token %}<input type="submit" value="Cancel"></form>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h4 style="font-style: italic">No transactions currently being processed by Dwolla.</h4>
    {% endif %}
    <br>
    <br>
    {% if failed_transactions %}
        <h2>Failed Dwolla transactions</h2>
        <br>
        <table width="100%" class="admin-table">
            <tr>
                <th>
                    Buyer
                </th>
                <th>
                    Seller
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Fee
                </th>
                <th>
                    Dwolla Status
                </th>
            </tr>
            {% for transaction in failed_transactions %}
            <tr>
                <td>
                    {{ transaction.deal.buyer.email }}
                </td>
                <td>
                    {{ transaction.deal.seller.email }}
                </td>
                <td>
                    {{ transaction.paid_to_seller }}
                </td>
                <td>
                    {{ transaction.fee }}
                </td>
                <td>
                    {{ transaction.status }}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
    <br>
    <br>
    <br>
    <p><h1>COMMUNITY SOLAR ACCOUNTS</h1></p>
    {% if community_solar_accounts %}
        <br>
            <table width="100%" class="admin-table">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Email
                    </th>
                </tr>
                {% for account in community_solar_accounts %}
                <tr>
                    <td>
                        {{ account.name }}
                    </td>
                    <td>
                        {{ account.email }}
                    </td>
                </tr>
                {% empty %}
                    <i><h3>No community solar accounts</h3></i>
                {% endfor %}
            </table>
    {% else %}
        <i><h3>No community solar accounts created.</h3></i>
    {% endif %}
    <br>
    <button id="modalButton">Create New Account</button>
    <!-- The Modal -->
    <div id="csaModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content" style="margin:5%">
            <div class="modal-header">
                <span class="close">&times;</span>
                <h2>Add Community Solar Facility Account</h2>
            </div>
            <form class="modal-body" method="POST" action="{% url "rest_framework:add_community_solar" %} ">
                {% csrf_token %}
                <p>
                    <input type="text" placeholder="Name" name="name" required="true">
                </p>
                <br>
                <p>
                    <input type="text" placeholder="Address" name="address" required="true">
                </p>
                <br>
                <p>
                    <input type="text" placeholder="City" name="city" required="true">
                </p>
                <br>
                <p>
                    <input type="text" placeholder="State" name="state" required="true">
                </p>
                <br>
                <p>
                    <input type="text" placeholder="Zip Code" name="zip_code" required="true">
                </p>
                <br>
                <br>
                <p>
                    <input type="text" placeholder="Email" name="email" required="true">
                </p>
                <br>
                <p>
                    <input type="text" placeholder="Temporary Password" name="password">
                </p>
                <br>
                <p class="pull-right">
                    <input type="submit" value="Submit">
                </p>
                <br>
            </form>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>

{% endblock %}

templates/errorpage.html
{% extends "account/base.html" %}
{% load staticfiles %}
{% block content %}
  <h1>ERROR</h1>
  <b>{{ error }}</b>
{% endblock %}

templates/user_dashboard.html
{% extends 'account/base.html' %}

{% block content %}
<div class="dashboard-wrapper">
  <p class="pull-right"><a href="/">Back to Home &rarr;</a></p>

  <h2>My Transactions</h2>
  {% if is_seller %}
  <p class="pull-right"><b>Balance</b>:
    {% if balance %}
      &dollar;{{ balance|floatformat:-2 }}
    {% else %}
      &dollar;0
    {% endif %}</p>
  {% endif %}

  <p>Please select a status by clicking</p>
  <ul class="filter-list">
    {% if request.GET.status %}
      <li><a href="/dashboard/">Any Status</a></li>
    {% else %}
      <li class="active"><a href="#">Any Status</a></li>
    {% endif %}

    {% for status, status_title in status_filter_list %}
      {% ifequal request.GET.status status %}
        <li class="active"><a href="#">{{ status_title }}</a></li>
      {% else %}
        <li><a href="?status={{ status }}">{{ status_title }}</a></li>
      {% endifequal %}
    {% endfor %}
  </ul>

  <p class="note">* Transactions will be processed on the 15th of the month</p>
  <table width="100%" class="admin-table">
      <tr>
          <th>Buyer</th>
          <th>Seller</th>
          <th>Amount</th>
          <th>Fee</th>
          <th>Dwolla Status</th>
          <th>Created on</th>
      </tr>
      {% for t in transactions %}
      <tr>
          <td>{{ t.deal.buyer.email }}</td>
          <td>{{ t.deal.seller.email }}</td>
          <td>{{ t.paid_to_seller }}</td>
          <td>{{ t.fee }}</td>
          <td>{{ t.status }}</td>
          <td>{{t.created_on|date:"SHORT_DATE_FORMAT"}} {{ t.created_on|time:"h:i a" }}</td>

          {% if t.is_cancelable_status %}
          <td>
            <form method="POST" action="{% url "rest_framework:cancel_transaction" t.id %}" class="cancel-trans-frm">
              {% csrf_token %}
              <input type="submit" value="Cancel">
            </form>
          </td>
          {% endif %}
      </tr>
      {% empty %}
        <tr>
          <td colspan="6" align="center">No transactions</td>
        </tr>
      {% endfor %}
  </table>
</div>
{% endblock %}

templates/utility_mock.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en" data-ng-app="mySunBuddy">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="description" content="" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta http-equiv="refresh" content="5;url=/utility_api_callback?referral=mock" />
  <title>MySunBuddy</title>
  <!-- CSS -->
  {% compress css %}
  <link href="{% static 'css/fonts.css'%}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/screen.css'%}" rel="stylesheet">
  <link href="{% static 'css/loading-bar.css'%}" rel="stylesheet">
  <link href="{% static 'css/toastr.css'%}" rel="stylesheet">
  <link href="{% static 'css/app.css'%}" rel="stylesheet">
  {% endcompress %}

</head>
<body>
  <p>Authenticating with Utility API and redirecting...</p>
</body>
</html>

templates/view_account_credit.html
{% extends "account/base.html" %}
{% load staticfiles %}
{% block content %}

<p><h2>SET MANUAL CREDITS FOR ACCOUNT</h2></p>
<br>
<p>By setting average monthly credit here, you will override the (negative) value for monthly credit calculated from API bills.</p>
<p>Setting a new percentage of credit to sell is optional.</p>

    <form method="POST" action="{% url 'rest_framework:edit_account_credits' account.id %}" class="">
      {% csrf_token %}
      <div class="form-group">
          <label for="average_monthly_credit"> New Average Monthly Credit (required) *: </label>
          <br>
          <input type="number" min="0" required id="average_monthly_credit" name="average_monthly_credit" value="{{ account.average_monthly_credit }}">
      </div>
      <div class="form-group">
          <label for="credit_to_sell_percent"> Percentage of credit to sell (default 100%): </label>
          <br>
          <input type="number" min="0" max="100" id="credit_to_sell_percent" name="credit_to_sell_percent" value="{{ account.credit_to_sell_percent }}">
      </div>
      <input type="submit" class="btn btn-secondary text-uppercase" value="Save" />
    </form>

{% endblock %}

templates/view_accounts.html
{% extends "account/base.html" %}
{% load staticfiles %}
{% block content %}

<p><h2>ALL ACCOUNTS</h2></p>
<br>
  <table width="100%" style="border: 1px solid black;">
    <tr style="border: 1px solid black; background-color: gray">
      <th>
        <i>Email Address</i>
      </th>
      <th>
        <i>Role</i>
      </th>
      <th>
        <i>Completed</i>
      </th>
    </tr>
    {% for account in accounts %}
    <tr style="border: 1px solid black;">
      <td>
          {{ account.email }}
      </td>
      <td>
          {{ account.role }}
      </td>
      <td>
        {% if account.has_utility_access and account.has_verified_funding %}
        <b>YES</b>
        {% else %}
          NO
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </table>
  <br>
  <br>
  <br>
  <br>

{% endblock %}